"""workout_log - user realtionship

Revision ID: 0e5470993f0e
Revises: 48d0423b4033
Create Date: 2026-09-22 10:59:34.276972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5470993f0e'
down_revision: Union[str, Sequence[str], None] = '48d0423b4033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_logs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('workout_log_user_id_fkey', 'workout_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workout_log_user_id_fkey', 'workout_logs', type_='foreignkey')
    op.drop_column('workout_logs', 'user_id')
    # ### end Alembic commands ###
