"""exercise ownership

Revision ID: 12268650ee57
Revises: ef6d7e92b686
Create Date: 2026-08-14 11:39:21.303917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12268650ee57'
down_revision: Union[str, Sequence[str], None] = 'ef6d7e92b686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('exercises', sa.Column('trainer_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_user_exercise_id', 'exercises', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_trainer_exercise_id', 'exercises', 'trainers', ['trainer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_exercise_id', 'exercises', type_='foreignkey')
    op.drop_constraint('fk_trainer_exercise_id', 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'trainer_id')
    op.drop_column('exercises', 'user_id')
    # ### end Alembic commands ###
