"""kekw

Revision ID: 136db99bb582
Revises: 0e5470993f0e
Create Date: 2026-09-25 11:20:27.148145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '136db99bb582'
down_revision: Union[str, Sequence[str], None] = '0e5470993f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'main_muscles',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.JSON(),
               postgresql_using="to_json(main_muscles)",)
    op.alter_column('exercises', 'side_muscles',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.JSON(),
               postgresql_using="to_json(side_muscles)",)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'side_muscles',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               postgresql_using=(
                "ARRAY(SELECT json_array_elements_text(side_muscles::json))",
        ))
    op.alter_column('exercises', 'main_muscles',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               postgresql_using=(
                "ARRAY(SELECT json_array_elements_text(main_muscles::json))",
        ))
    # ### end Alembic commands ###
