"""cascade deletes on fk in diaries

Revision ID: 2575e168be3f
Revises: 08a678593cc4
Create Date: 2026-05-08 17:08:17.232255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2575e168be3f'
down_revision: Union[str, Sequence[str], None] = '08a678593cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_diary_user_id_fkey'), 'users_diary', type_='foreignkey')
    op.drop_constraint(op.f('users_diary_meal_id_fkey'), 'users_diary', type_='foreignkey')
    op.create_foreign_key(None, 'users_diary', 'meals', ['meal_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users_diary', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_diary', type_='foreignkey')
    op.drop_constraint(None, 'users_diary', type_='foreignkey')
    op.create_foreign_key(op.f('users_diary_meal_id_fkey'), 'users_diary', 'meals', ['meal_id'], ['id'])
    op.create_foreign_key(op.f('users_diary_user_id_fkey'), 'users_diary', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
