"""diaries as snapshots and trainer-products relationships

Revision ID: 2792a736a318
Revises: 7116cbee9b30
Create Date: 2026-07-23 18:43:52.517402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2792a736a318'
down_revision: Union[str, Sequence[str], None] = '7116cbee9b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diaries_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_category', sa.String(), nullable=False),
    sa.Column('meal_name', sa.String(), nullable=False),
    sa.Column('meal_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diaries_meal_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diary_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kcal_per_100g', sa.Integer(), nullable=False),
    sa.Column('protein_per_100g', sa.Integer(), nullable=False),
    sa.Column('fat_per_100g', sa.Integer(), nullable=False),
    sa.Column('carbs_per_100g', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diary_id'], ['diaries_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('grams', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users_diary')
    op.drop_table('meals_products')
    op.add_column('products', sa.Column('trainer_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_products_trainer_id_trainers', 'products', 'trainers', ['trainer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_products_trainer_id_trainers', 'products', type_='foreignkey')
    op.drop_column('products', 'trainer_id')
    op.create_table('meals_products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grams', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('meals_products_meal_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('meals_products_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('meals_products_pkey'))
    )
    op.create_table('users_diary',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meal_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('users_diary_meal_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('users_diary_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('users_diary_pkey'))
    )
    op.drop_table('meal_products')
    op.drop_table('diaries_meal_products')
    op.drop_table('diaries_entry')
    # ### end Alembic commands ###
