"""main and side muscles adjusted

Revision ID: 2cb812ab7843
Revises: 3e5300ac7c95
Create Date: 2026-08-14 10:57:51.090787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cb812ab7843'
down_revision: Union[str, Sequence[str], None] = '3e5300ac7c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('main_muscles', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('exercises', sa.Column('side_muscles', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('exercises', 'side_muscle')
    op.drop_column('exercises', 'main_muscle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('main_muscle', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('exercises', sa.Column('side_muscle', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('exercises', 'side_muscles')
    op.drop_column('exercises', 'main_muscles')
    # ### end Alembic commands ###
