"""source for training plans

Revision ID: 3e5300ac7c95
Revises: f4d3d086530c
Create Date: 2026-08-14 10:07:06.979333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5300ac7c95'
down_revision: Union[str, Sequence[str], None] = 'f4d3d086530c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_plans', sa.Column('source', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_plans', 'source')
    # ### end Alembic commands ###
