"""start_time and end_time for workout_log and fixed reps in sets - planned and performed

Revision ID: 48d0423b4033
Revises: e661ff13c1cb
Create Date: 2026-09-22 10:53:02.345931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48d0423b4033'
down_revision: Union[str, Sequence[str], None] = 'e661ff13c1cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_log_exercise_sets', sa.Column('planned_repetitions', sa.Integer(), nullable=False))
    op.add_column('workout_log_exercise_sets', sa.Column('performed_repetitions', sa.Integer(), nullable=False))
    op.drop_column('workout_log_exercise_sets', 'repetitions')
    op.add_column('workout_logs', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('workout_logs', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.drop_column('workout_logs', 'duration')
    op.drop_column('workout_logs', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_logs', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('workout_logs', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('workout_logs', 'end_time')
    op.drop_column('workout_logs', 'start_time')
    op.add_column('workout_log_exercise_sets', sa.Column('repetitions', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('workout_log_exercise_sets', 'performed_repetitions')
    op.drop_column('workout_log_exercise_sets', 'planned_repetitions')
    # ### end Alembic commands ###
