"""start and finish time added to trainer_client

Revision ID: 5ffa12a91631
Revises: 2b56e042599c
Create Date: 2026-07-17 17:18:41.486029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ffa12a91631'
down_revision: Union[str, Sequence[str], None] = '2b56e042599c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainer_client', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('trainer_client', sa.Column('finished_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainer_client', 'finished_at')
    op.drop_column('trainer_client', 'started_at')
    # ### end Alembic commands ###
