"""cascades adjusted, meal is_active added

Revision ID: 61d207763cf9
Revises: 2575e168be3f
Create Date: 2026-05-09 12:18:44.710044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d207763cf9'
down_revision: Union[str, Sequence[str], None] = '2575e168be3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.drop_constraint(op.f('meals_user_id_fkey'), 'meals', type_='foreignkey')
    op.create_foreign_key(None, 'meals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_diary_meal_id_fkey'), 'users_diary', type_='foreignkey')
    op.create_foreign_key(None, 'users_diary', 'meals', ['meal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_diary', type_='foreignkey')
    op.create_foreign_key(op.f('users_diary_meal_id_fkey'), 'users_diary', 'meals', ['meal_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'meals', type_='foreignkey')
    op.create_foreign_key(op.f('meals_user_id_fkey'), 'meals', 'users', ['user_id'], ['id'])
    op.drop_column('meals', 'is_active')
    # ### end Alembic commands ###
