"""user_id added to ai_details

Revision ID: 70153a217878
Revises: ea94c8e8f8c3
Create Date: 2026-07-06 19:29:29.052618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70153a217878'
down_revision: Union[str, Sequence[str], None] = 'ea94c8e8f8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_details', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ai_details', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_details', type_='foreignkey')
    op.drop_column('ai_details', 'user_id')
    # ### end Alembic commands ###
