"""fix: trainer_client trainer_id FK to trainers.id

Revision ID: b482130854f0
Revises: 5ffa12a91631
Create Date: 2026-07-17 17:47:26.751265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b482130854f0'
down_revision: Union[str, Sequence[str], None] = '5ffa12a91631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('trainer_client_trainer_id_fkey'), 'trainer_client', type_='foreignkey')
    op.create_foreign_key(None, 'trainer_client', 'trainers', ['trainer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainer_client', type_='foreignkey')
    op.create_foreign_key(op.f('trainer_client_trainer_id_fkey'), 'trainer_client', 'users', ['trainer_id'], ['id'])
    # ### end Alembic commands ###
