"""MealProducts cascade delete when Meal delete

Revision ID: bae623539a23
Revises: 8259c1fc1f6d
Create Date: 2026-04-24 17:22:17.066720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae623539a23'
down_revision: Union[str, Sequence[str], None] = '8259c1fc1f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('meals_products_meal_id_fkey'), 'meals_products', type_='foreignkey')
    op.create_foreign_key(None, 'meals_products', 'meals', ['meal_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meals_products', type_='foreignkey')
    op.create_foreign_key(op.f('meals_products_meal_id_fkey'), 'meals_products', 'meals', ['meal_id'], ['id'])
    # ### end Alembic commands ###
