"""source column for meals

Revision ID: cdedb468093c
Revises: f417f4dd89aa
Create Date: 2026-08-01 17:45:11.056332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdedb468093c'
down_revision: Union[str, Sequence[str], None] = 'f417f4dd89aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meals', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meals', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
