"""unit_order for training units

Revision ID: e661ff13c1cb
Revises: 12268650ee57
Create Date: 2026-08-18 19:01:44.209097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e661ff13c1cb'
down_revision: Union[str, Sequence[str], None] = '12268650ee57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_units', sa.Column('unit_order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_units', 'unit_order')
    # ### end Alembic commands ###
