"""new table for ai integration details

Revision ID: ea94c8e8f8c3
Revises: c0ee1accb33e
Create Date: 2026-07-06 19:11:01.156821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea94c8e8f8c3'
down_revision: Union[str, Sequence[str], None] = 'c0ee1accb33e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_session', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('message_role', sa.String(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_details')
    # ### end Alembic commands ###
