"""source column for meals

Revision ID: f417f4dd89aa
Revises: 7f6136580467
Create Date: 2026-08-01 17:41:48.401328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f417f4dd89aa'
down_revision: Union[str, Sequence[str], None] = '7f6136580467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'source')
    # ### end Alembic commands ###
