"""grams for diaries_meal_products

Revision ID: fb37144ee9e9
Revises: 2792a736a318
Create Date: 2026-07-23 19:05:11.727082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb37144ee9e9'
down_revision: Union[str, Sequence[str], None] = '2792a736a318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diaries_meal_products', sa.Column('grams', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diaries_meal_products', 'grams')
    # ### end Alembic commands ###
